import { library } from '@fortawesome/fontawesome-svg-core';
import { 
  faHome,
  faNewspaper,
  faHeart,
  faUser,
  faSearch,
  faBars,
  faTimes,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faPlus,
  faEdit,
  faTrash,
  faSave,
  faCancel,
  faShare,
  faComment,
  faThumbsUp,
  faThumbsDown,
  faBookmark,
  faEye,
  faEyeSlash,
  faCog,
  faSignOutAlt,
  faSignInAlt,
  faUserPlus,
  faSpinner,
  faExclamationTriangle,
  faCheckCircle,
  faInfoCircle,
  faTimesCircle,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faCalendar,
  faClock,
  faGlobe,
  faLanguage,
  faBell,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faCamera,
  faImage,
  faUpload,
  faDownload,
  faCopy,
  faExternalLinkAlt,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faRefresh,
  faStar,
  faStarHalfAlt,
  faTag,
  faTags,
  faFolder,
  faFolderOpen,
  faFile,
  faFileAlt,
  faLink,
  faUnlink,
  faLock,
  faUnlock,
  faShield,
  faUserShield,
  faRobot,
  faComments,
  faPaperPlane,
  faMicrophone,
  faKeyboard,
  faLightbulb,
  faQuestionCircle,
  faGraduationCap,
  faTrophy,
  faGamepad,
  faMusic,
  faFilm,
  faBook,
  faGavel,
  faMedkit,
  faFlask,
  faFootballBall,
  faBasketballBall,
  faBaseballBall,
  faDollarSign,
  faChartLine,
  faBuilding,
  faIndustry,
  faLaptop,
  faMobile,
  faWifi,
  faCloud,
  faDatabase,
  faServer,
  faCode,
  faBug,
  faTerminal,
  faGithub,
  faReact,
  faGoogle,
  faFacebook,
  faTwitter,
  faInstagram,
  faLinkedin,
  faYoutube
} from '@fortawesome/free-solid-svg-icons';

import {
  faHeart as faHeartRegular,
  faBookmark as faBookmarkRegular,
  faUser as faUserRegular,
  faComments as faCommentsRegular,
  faThumbsUp as faThumbsUpRegular,
  faThumbsDown as faThumbsDownRegular,
  faStar as faStarRegular,
  faEye as faEyeRegular,
  faCalendar as faCalendarRegular,
  faClock as faClockRegular,
  faImage as faImageRegular,
  faFile as faFileRegular,
  faFolder as faFolderRegular,
  faEnvelope as faEnvelopeRegular,
  faCheckCircle as faCheckCircleRegular,
  faTimesCircle as faTimesCircleRegular
} from '@fortawesome/free-regular-svg-icons';

import {
  faGithub as faGithubBrands,
  faGoogle as faGoogleBrands,
  faFacebook as faFacebookBrands,
  faTwitter as faTwitterBrands,
  faInstagram as faInstagramBrands,
  faLinkedin as faLinkedinBrands,
  faYoutube as faYoutubeBrands,
  faReact as faReactBrands,
  faNode as faNodeBrands,
  faApple as faAppleBrands,
  faAndroid as faAndroidBrands,
  faWindows as faWindowsBrands,
  faLinux as faLinuxBrands
} from '@fortawesome/free-brands-svg-icons';

// Add icons to the library
library.add(
  // Solid icons
  faHome,
  faNewspaper,
  faHeart,
  faUser,
  faSearch,
  faBars,
  faTimes,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faPlus,
  faEdit,
  faTrash,
  faSave,
  faCancel,
  faShare,
  faComment,
  faThumbsUp,
  faThumbsDown,
  faBookmark,
  faEye,
  faEyeSlash,
  faCog,
  faSignOutAlt,
  faSignInAlt,
  faUserPlus,
  faSpinner,
  faExclamationTriangle,
  faCheckCircle,
  faInfoCircle,
  faTimesCircle,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faCalendar,
  faClock,
  faGlobe,
  faLanguage,
  faBell,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faCamera,
  faImage,
  faUpload,
  faDownload,
  faCopy,
  faExternalLinkAlt,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faRefresh,
  faStar,
  faStarHalfAlt,
  faTag,
  faTags,
  faFolder,
  faFolderOpen,
  faFile,
  faFileAlt,
  faLink,
  faUnlink,
  faLock,
  faUnlock,
  faShield,
  faUserShield,
  faRobot,
  faComments,
  faPaperPlane,
  faMicrophone,
  faKeyboard,
  faLightbulb,
  faQuestionCircle,
  faGraduationCap,
  faTrophy,
  faGamepad,
  faMusic,
  faFilm,
  faBook,
  faGavel,
  faMedkit,
  faFlask,
  faFootballBall,
  faBasketballBall,
  faBaseballBall,
  faDollarSign,
  faChartLine,
  faBuilding,
  faIndustry,
  faLaptop,
  faMobile,
  faWifi,
  faCloud,
  faDatabase,
  faServer,
  faCode,
  faBug,
  faTerminal,

  // Regular icons
  faHeartRegular,
  faBookmarkRegular,
  faUserRegular,
  faCommentsRegular,
  faThumbsUpRegular,
  faThumbsDownRegular,
  faStarRegular,
  faEyeRegular,
  faCalendarRegular,
  faClockRegular,
  faImageRegular,
  faFileRegular,
  faFolderRegular,
  faEnvelopeRegular,
  faCheckCircleRegular,
  faTimesCircleRegular,

  // Brand icons
  faGithubBrands,
  faGoogleBrands,
  faFacebookBrands,
  faTwitterBrands,
  faInstagramBrands,
  faLinkedinBrands,
  faYoutubeBrands,
  faReactBrands,
  faNodeBrands,
  faAppleBrands,
  faAndroidBrands,
  faWindowsBrands,
  faLinuxBrands
);

// Icon mapping for easy access
export const icons = {
  // Navigation
  home: 'home',
  news: 'newspaper',
  favorites: 'heart',
  profile: 'user',
  search: 'search',
  menu: 'bars',
  close: 'times',
  
  // Actions
  edit: 'edit',
  delete: 'trash',
  save: 'save',
  cancel: 'times',
  share: 'share',
  upload: 'upload',
  download: 'download',
  copy: 'copy',
  refresh: 'sync-alt',
  
  // UI Elements
  chevronDown: 'chevron-down',
  chevronUp: 'chevron-up',
  chevronLeft: 'chevron-left',
  chevronRight: 'chevron-right',
  arrowUp: 'arrow-up',
  arrowDown: 'arrow-down',
  plus: 'plus',
  
  // Content
  comment: 'comment',
  like: 'thumbs-up',
  bookmark: 'bookmark',
  view: 'eye',
  star: 'star',
  tag: 'tag',
  
  // User
  signIn: 'sign-in-alt',
  signOut: 'sign-out-alt',
  signUp: 'user-plus',
  settings: 'cog',
  shield: 'shield-alt',
  
  // Status
  loading: 'spinner',
  success: 'check-circle',
  error: 'times-circle',
  warning: 'exclamation-triangle',
  info: 'info-circle',
  
  // Categories
  business: 'chart-line',
  technology: 'laptop',
  sports: 'football-ball',
  science: 'flask',
  health: 'medkit',
  entertainment: 'film',
  
  // AI/Chat
  robot: 'robot',
  chat: 'comments',
  send: 'paper-plane',
  microphone: 'microphone',
  
  // Media
  image: 'image',
  camera: 'camera',
  video: 'film',
  audio: 'music',
  
  // Time
  calendar: 'calendar-alt',
  clock: 'clock'
};

export default library;
